services:
  web:
    build:
      context: ./airdb-web
      dockerfile: Dockerfile
    ports:
      - "8001:80"
    restart: always

  airbox:
    container_name: airdb_airBox
    build:
      context: ./airdb-airBox
      dockerfile: Dockerfile
    restart: always
    environment:
      - MOE_API_KEY
      - GOOGLE_API_KEY
    
  db:
    container_name: airdb_db
    image: mysql:lts
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
  
  aqi:
    container_name: airdb_aqi
    build:
      context: ./airdb-aqi
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./airdb-aqi/airdb.db:/mnt/aqi-app/airdb.db
  
  tb:
    container_name: airdb_TB
    build:
      context: ./airdb-TB
      dockerfile: Dockerfile
    restart: always
  
  copd:
    container_name: airdb_COPD
    build:
      context: ./airdb-COPD
      dockerfile: Dockerfile
    restart: always
  