services:
  web:
    build:
      context: ./airdb-web
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - aqi
      - airbox
      - tb
      - copd
      - db
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro

  airbox:
    container_name: airdb_airBox
    build:
      context: ./airdb-airBox
      dockerfile: Dockerfile
    restart: always
    environment:
      - MOE_API_KEY
      - GOOGLE_API_KEY
    volumes:
      - /etc/localtime:/etc/localtime:ro
    
  db:
    container_name: airdb_db
    image: mysql:lts
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
    volumes:
      - airdb_db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
  
  aqi:
    container_name: airdb_aqi
    build:
      context: ./airdb-aqi
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./airdb-aqi/airdb.db:/mnt/aqi-app/airdb.db
      - /etc/localtime:/etc/localtime:ro
  
  tb:
    container_name: airdb_TB
    build:
      context: ./airdb-TB
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
  
  copd:
    container_name: airdb_COPD
    build:
      context: ./airdb-COPD
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
  
volumes:
  airdb_db:
    external: true
